version: '3.5'

services:

  quarkus:
    image: felipewind/quarkus-monitor-demo:1.0-${QUARKUS_MODE:-jvm}
    container_name: quarkus-monitor-demo
    build:
      context: quarkus
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    # environment:
    #   KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    network_mode: "host"
    # ports:
    #   - "8080:8080"
    # networks:
    #   - quarkus-monitor-demo-network

  mock-server:
    image: felipewind/mock-server-quarkus-monitor:1.0-${QUARKUS_MODE:-jvm}
    container_name: mock-server-quarkus-monitor
    build:
      context: mock-server
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    # environment:
    #   KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    network_mode: "host"
    # ports:
    #   - "8090:8090"
    # networks:
    #   - quarkus-monitor-demo-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-quarkus-monitor
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.listen-address=127.0.0.1:9090'
    network_mode: "host"
    # ports:
    #   - "9090:9090"
#    networks:
#      - quarkus-monitor-demo-network
#
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-quarkus-monitor
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/data
    environment:
      GF_SERVER_HTTP_ADDR: "127.0.0.1"
    network_mode: "host"
    # ports:
    #   - 3000:3000
#    networks:
#      - quarkus-monitor-demo-network

volumes:
  prometheus_data:
  grafana_data:

# networks:
#   quarkus-monitor-demo-network:
#     name: kafkaquickstart
