# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
#deleteDatasources:
#  - name: Graphite
#    orgId: 1

datasources:
- name: Prometheus-App
  type: prometheus
  access: proxy
  isDefault: true
  url: http://0.0.0.0:9090
  editable: true