{
 "title": "Quarkus Monitor",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Accounts ID - Transactions per second on the last 1 minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(dependency_request_seconds_count{addr=\"/accounts/{id}\"}[1m])",
     "legendFormat": "Transactions per minute"
    }
   ]
  },
  {
   "title": "Accounts ID - Average time of transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(sum_over_time(dependency_request_seconds_sum{addr=\"/accounts/{id}\"}[1m]))\r\n/\r\nsum(sum_over_time(dependency_request_seconds_count{addr=\"/accounts/{id}\"}[1m]))"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "application_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Dependency up - Mock Server",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dependency_up{name=\"org.acme.MockInterface\"}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"quarkus-monitor-demo\"})"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(up{service=\"quarkus-monitor-demo\"})"
    }
   ]
  }
 ]
}