{
 "title": "Teste  - API Golden Signals and Business",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "qualityRule",
    "label": "Régua de Qualidade",
    "query": "0.01, 0.05, 0.5, 0.9, 0.95, 0.99, 0.999"
   },
   {
    "name": "quarkusDemo",
    "label": "Service Análise Automática",
    "query": "label_values(up{service=~\".*quarkus-monitor-demo.*\"}, service)"
   }
  ]
 },
 "panels": [
  { "title": "Disponibilidade", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "API", "type": "text", "gridPos": { "h": 1, "w": 7, "x": 0, "y": 1 }, "content": "\n" },
  { "title": "Sidecar - Test", "type": "text", "gridPos": { "h": 1, "w": 7, "x": 7, "y": 1 }, "content": "\n" },
  {
   "title": "Instances",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "up{service=\"$quarkusDemo\", endpoint=\"quarkus-http\"}",
     "legendFormat": "API {{instance}}"
    },
    {
     "expr": "up{service=\"$quarkusDemo\", endpoint=\"test-http\"}",
     "legendFormat": "Test {{instance}}"
    },
    {
     "expr": "sum(up{service=\"$quarkusDemo\", endpoint=\"quarkus-http\"})",
     "legendFormat": "Total de Instâncias API"
    },
    {
     "expr": "sum(up{service=\"$quarkusDemo\", endpoint=\"test-http\"})",
     "legendFormat": "Total de Instâncias"
    }
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{service=\"$quarkusDemo\"})"
    }
   ]
  },
  {
   "title": "Versão",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 2 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, sort_desc(application_quarkus_demo))",
     "legendFormat": "{{apiVersion}}"
    }
   ]
  },
  {
   "title": "Instâncias",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 5, "y": 2 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{service=\"$quarkusDemo\", endpoint=\"quarkus-http\"})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{service=\"$quarkusDemo\", endpoint=\"test-http\"})"
    }
   ]
  },
  {
   "title": "Versão",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1,application_health_check_provimento_up{service=\"$quarkusDemo\"})",
     "legendFormat": "{{serviceVersion}}"
    }
   ]
  },
  {
   "title": "Instâncias",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 2 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{service=\"$quarkusDemo\", endpoint=\"test-http\"})"
    }
   ]
  },
  {
   "title": "Versões Disponíveis",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 4 },
   "targets": [
    {
     "expr": "count(application_quarkus_demo)by(apiVersion) > 0",
     "legendFormat": "{{apiVersion}}"
    }
   ]
  },
  { "title": "Provimento teste", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
   "content": "<div style=\" text-align: center; color:\"red\";><br><h3><b> <font color=\"#D8AB52\">4GS</font><font color=\"#5281D8\">Tráfego</font> </b></h3><br></div> \n\n\n\n",
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 9 },
   "content": "<div style=\" text-align: center;\"><br><h3><b> <font color=\"#D8AB52\">4GS</font><font color=\"#5281D8\">Latência</font>  </b></h3><br></div>\n\n\n\n",
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "content": "<div style=\"text-align: center;\"><br><h3><b>  <font color=\"#D8AB52\">4GS</font><font color=\"#5281D8\">Erros</font> </b></h3><br></div>\n\n\n\n",
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "content": "<div style=\" text-align: center;\"><br><h3><b> <font color=\"#D8AB52\">4GS</font><font color=\"#5281D8\">Saturação</font> </b></h3><br></div>\n\n\n\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "Quantidade de Requisições",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(increase(application_quarkus_demo_requests_counter_total[60s]))"
    }
   ]
  },
  {
   "title": "Percentil do Tempo de Resposta",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(application_quarkus_demo_successful_seconds_count) by (quantile)",
     "legendFormat": "Bem sucedidas"
    },
    {
     "expr": "avg(application_quarkus_demo_unsuccessful_seconds_count) by (quantile)",
     "legendFormat": "Erro"
    }
   ]
  },
  {
   "title": "Percentual de Exceptions",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "(sum(application_quarkus_demo_exception_quarkusexception_counter_total) + sum(application_quarkus_demo_exception_counter_total) + sum(application_quarkus_demo_exception_jdbcexception_counter_total)) * 100 / sum(application_quarkus_demo_requests_counter_total)"
    }
   ]
  },
  {
   "title": "Utilização CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"quarkus-demo-api\"}) / \nsum(kube_resourcequota{resource=\"requests.cpu\",type=\"hard\",namespace=\"quarkus-demo-api\"}) * 100"
    }
   ]
  },
  {
   "title": "Memória",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 17 },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.memory\",type=\"used\",namespace=\"quarkus-demo-api\"}) / \nsum(kube_resourcequota{resource=\"requests.memory\",type=\"hard\",namespace=\"quarkus-demo-api\"}) * 100"
    }
   ]
  },
  {
   "title": "Contador",
   "type": "graph",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(application_quarkus_demo_requests_counter_total)"
    }
   ]
  },
  {
   "title": "Delta (max - min) no período",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 18 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(application_quarkus_demo_requests_counter_total)"
    }
   ]
  },
  {
   "title": "Requests/segundo",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(application_quarkus_demo_requests_counter_total[5m]))"
    }
   ]
  },
  {
   "title": "Tempo de Resposta - Sucesso",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(application_quarkus_demo_successful_seconds{quantile=\"$qualityRule\"})"
    }
   ]
  },
  {
   "title": "Tempo de Resposta - Erro",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 18 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(application_quarkus_demo_unsuccessful_seconds{quantile=\"$qualityRule\"})"
    }
   ]
  },
  {
   "title": "Contador de Exceptions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(application_quarkus_demo_exception_quarkusexception_counter_total) + sum(application_quarkus_demo_exception_counter_total) + sum(application_quarkus_demo_exception_jdbcexception_counter_total))"
    }
   ]
  }
 ]
}